services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: todo_backend
    volumes:
      - backend_data:/app/db_data
      - ./backend/db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
    ports:               
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/?next=/admin/"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: todo_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=/api

volumes:
  backend_data:
